FROM swr.cn-east-3.myhuaweicloud.com/paas_perf/memtier:1.3.0-centos7
#RUN yum install -y autoconf automake make gcc-c++ pcre-devel zlib-devel libevent-devel openssl-devel
#ADD 1.3.0.tar.gz /
#RUN cd memtier_benchmark-1.3.0; autoreconf -ivf; ./configure; make; make install
